package com.medic.app.mesh

/**
 * A message on the offline mesh.
 *
 * Design constraints, all driven by the deployment this app assumes -- no
 * infrastructure, no internet, and a radio link measured in tens of metres:
 *
 *  - **Self-identifying.** [id] is generated by the sender and never reused, so
 *    any node can recognise a message it has already seen without coordinating
 *    with anyone.
 *  - **Hop-limited.** [ttl] decrements on every forward. Without it a message
 *    circulating between three nodes that can all hear each other never stops.
 *  - **Small.** BLE advertisement and GATT payloads are tiny. The body is
 *    capped at [MAX_BODY_BYTES] so a message always fits a single write and the
 *    protocol never needs fragmentation and reassembly.
 *  - **No delivery guarantee.** Nothing here acknowledges. On a mesh of people
 *    walking around, a node that was in range a moment ago may simply be gone.
 *    The UI must show what was *sent*, never claim it was received.
 */

/** What a message is for. Priority governs eviction when the store is full. */
enum class MessageKind(val priority: Int) {
    /** A casualty or medic asking for help. Never evicted while anything else remains. */
    SOS(0),

    /** Position or status broadcast to whoever can hear it. */
    BEACON(1),

    /** Ordinary person-to-person text. */
    CHAT(2),
}

data class MeshMessage(
    val id: String,
    val senderId: String,
    val senderName: String,
    val kind: MessageKind,
    val body: String,
    val sentAtMillis: Long,
    val ttl: Int = DEFAULT_TTL,
    /** Hops taken so far. 0 means it came straight from the sender. */
    val hops: Int = 0,
) {
    init {
        require(id.isNotBlank()) { "message id must not be blank" }
        require(ttl >= 0) { "ttl must not be negative" }
        require(hops >= 0) { "hops must not be negative" }
    }

    /**
     * True when the node holding this copy may transmit it once more.
     *
     * [ttl] counts *further hops permitted*, so a copy holding ttl = 1 may be
     * passed on exactly once and the node that receives it may not.
     */
    val forwardable: Boolean get() = ttl > 0

    /**
     * This message as seen by a node that has just heard it.
     *
     * [hops] becomes that node's own distance from the origin -- the sender
     * transmits hops = 0, so the first node to hear it is 1 hop out. [ttl] drops
     * by one because the receiving node has one less hop to give.
     *
     * The stored copy and the onward transmission are the same value: what a
     * node holds is exactly what it is entitled to pass on. Whether it may pass
     * it on at all is [forwardable] on the copy that arrived.
     */
    fun asReceived(): MeshMessage =
        copy(hops = hops + 1, ttl = if (ttl > 0) ttl - 1 else 0)

    companion object {
        /**
         * Five hops. At a realistic BLE range of ~30 m that covers roughly
         * 150 m of chained nodes, which is the scale this is for -- a scattered
         * group, not a city. Higher values mostly multiply rebroadcast traffic.
         */
        const val DEFAULT_TTL = 5

        /** Fits comfortably inside a single BLE GATT write with header room. */
        const val MAX_BODY_BYTES = 180
    }
}
